import type { JsonObject, ToolAnnotations, ToolDefinitionSummary, ToolInput, ToolName } from "@mako-ai/contracts";
import {
  AskToolInputSchema,
  AskToolOutputSchema,
  AuthPathToolInputSchema,
  AuthPathToolOutputSchema,
  DbColumnsToolInputSchema,
  DbColumnsToolOutputSchema,
  DbFkToolInputSchema,
  DbFkToolOutputSchema,
  DbPingToolInputSchema,
  DbPingToolOutputSchema,
  DbRlsToolInputSchema,
  DbRlsToolOutputSchema,
  DbRpcToolInputSchema,
  DbRpcToolOutputSchema,
  DbTableSchemaToolInputSchema,
  DbTableSchemaToolOutputSchema,
  MakoHelpToolInputSchema,
  MakoHelpToolOutputSchema,
  ExportsOfToolInputSchema,
  ExportsOfToolOutputSchema,
  FileHealthToolInputSchema,
  FileHealthToolOutputSchema,
  FlowMapToolInputSchema,
  FlowMapToolOutputSchema,
  HealthTrendToolInputSchema,
  HealthTrendToolOutputSchema,
  ImplementationHandoffArtifactToolInputSchema,
  ImplementationHandoffArtifactToolOutputSchema,
  ReviewBundleArtifactToolInputSchema,
  ReviewBundleArtifactToolOutputSchema,
  TaskPreflightArtifactToolInputSchema,
  TaskPreflightArtifactToolOutputSchema,
  VerificationBundleArtifactToolInputSchema,
  VerificationBundleArtifactToolOutputSchema,
  IssuesNextToolInputSchema,
  IssuesNextToolOutputSchema,
  SessionHandoffToolInputSchema,
  SessionHandoffToolOutputSchema,
  SuggestToolInputSchema,
  SuggestToolOutputSchema,
  GraphNeighborsToolInputSchema,
  GraphNeighborsToolOutputSchema,
  GraphPathToolInputSchema,
  GraphPathToolOutputSchema,
  InvestigateToolInputSchema,
  InvestigateToolOutputSchema,
  ImportsCyclesToolInputSchema,
  ImportsCyclesToolOutputSchema,
  ImportsDepsToolInputSchema,
  ImportsDepsToolOutputSchema,
  ImportsHotspotsToolInputSchema,
  ImportsHotspotsToolOutputSchema,
  ImportsImpactToolInputSchema,
  ImportsImpactToolOutputSchema,
  RouteTraceToolInputSchema,
  RouteTraceToolOutputSchema,
  SchemaUsageToolInputSchema,
  SchemaUsageToolOutputSchema,
  SymbolsOfToolInputSchema,
  SymbolsOfToolOutputSchema,
  TenantLeakAuditToolInputSchema,
  TenantLeakAuditToolOutputSchema,
  ToolAnnotationsSchema,
  ToolHintsSchema,
  TraceFileToolInputSchema,
  TraceFileToolOutputSchema,
  WorkflowPacketToolInputSchema,
  WorkflowPacketToolOutputSchema,
  ChangePlanToolInputSchema,
  ChangePlanToolOutputSchema,
  AstFindPatternToolInputSchema,
  AstFindPatternToolOutputSchema,
  LiveTextSearchToolInputSchema,
  LiveTextSearchToolOutputSchema,
  LintFilesToolInputSchema,
  LintFilesToolOutputSchema,
  BiomeDiagnosticsToolInputSchema,
  BiomeDiagnosticsToolOutputSchema,
  EslintDiagnosticsToolInputSchema,
  EslintDiagnosticsToolOutputSchema,
  OxlintDiagnosticsToolInputSchema,
  OxlintDiagnosticsToolOutputSchema,
  TypeScriptDiagnosticsToolInputSchema,
  TypeScriptDiagnosticsToolOutputSchema,
  GitPrecommitCheckToolInputSchema,
  GitPrecommitCheckToolOutputSchema,
  RepoMapToolInputSchema,
  RepoMapToolOutputSchema,
  ContextPacketToolInputSchema,
  ContextPacketToolOutputSchema,
  ToolBatchInputSchema,
  ToolBatchToolOutputSchema,
  ProjectIndexStatusToolInputSchema,
  ProjectIndexStatusToolOutputSchema,
  ProjectIndexRefreshToolInputSchema,
  ProjectIndexRefreshToolOutputSchema,
  RuntimeTelemetryReportToolInputSchema,
  RuntimeTelemetryReportToolOutputSchema,
  AgentFeedbackToolInputSchema,
  AgentFeedbackToolOutputSchema,
  AgentFeedbackReportToolInputSchema,
  AgentFeedbackReportToolOutputSchema,
  RecallAnswersToolInputSchema,
  RecallAnswersToolOutputSchema,
  RecallToolRunsToolInputSchema,
  RecallToolRunsToolOutputSchema,
  RouteContextToolInputSchema,
  RouteContextToolOutputSchema,
  RpcNeighborhoodToolInputSchema,
  RpcNeighborhoodToolOutputSchema,
  TableNeighborhoodToolInputSchema,
  TableNeighborhoodToolOutputSchema,
  FindingAckToolInputSchema,
  FindingAckToolOutputSchema,
  FindingAckBatchToolInputSchema,
  FindingAckBatchToolOutputSchema,
  FindingAcksReportToolInputSchema,
  FindingAcksReportToolOutputSchema,
  DiagnosticRefreshToolInputSchema,
  DiagnosticRefreshToolOutputSchema,
  DbReefRefreshToolInputSchema,
  DbReefRefreshToolOutputSchema,
  DbReviewCommentToolInputSchema,
  DbReviewCommentToolOutputSchema,
  DbReviewCommentsToolInputSchema,
  DbReviewCommentsToolOutputSchema,
  EvidenceConfidenceToolInputSchema,
  EvidenceConfidenceToolOutputSchema,
  EvidenceConflictsToolInputSchema,
  EvidenceConflictsToolOutputSchema,
  ExtractRuleTemplateToolInputSchema,
  ExtractRuleTemplateToolOutputSchema,
  FileFactsToolInputSchema,
  FileFactsToolOutputSchema,
  FileFindingsToolInputSchema,
  FileFindingsToolOutputSchema,
  FilePreflightToolInputSchema,
  FilePreflightToolOutputSchema,
  ListReefRulesToolInputSchema,
  ListReefRulesToolOutputSchema,
  ProjectConventionsToolInputSchema,
  ProjectConventionsToolOutputSchema,
  ProjectDiagnosticRunsToolInputSchema,
  ProjectDiagnosticRunsToolOutputSchema,
  ProjectFactsToolInputSchema,
  ProjectFactsToolOutputSchema,
  ProjectFindingsToolInputSchema,
  ProjectFindingsToolOutputSchema,
  ProjectOpenLoopsToolInputSchema,
  ProjectOpenLoopsToolOutputSchema,
  ReefDiffImpactToolInputSchema,
  ReefDiffImpactToolOutputSchema,
  ReefInstructionsToolInputSchema,
  ReefInstructionsToolOutputSchema,
  ReefOverlayDiffToolInputSchema,
  ReefOverlayDiffToolOutputSchema,
  ReefInspectToolInputSchema,
  ReefInspectToolOutputSchema,
  ReefAgentStatusToolInputSchema,
  ReefAgentStatusToolOutputSchema,
  ReefKnownIssuesToolInputSchema,
  ReefKnownIssuesToolOutputSchema,
  ReefScoutToolInputSchema,
  ReefScoutToolOutputSchema,
  ReefWhereUsedToolInputSchema,
  ReefWhereUsedToolOutputSchema,
  RulePackValidateToolInputSchema,
  RulePackValidateToolOutputSchema,
  RuleMemoryToolInputSchema,
  RuleMemoryToolOutputSchema,
  VerificationStateToolInputSchema,
  VerificationStateToolOutputSchema,
  WorkingTreeOverlayToolInputSchema,
  WorkingTreeOverlayToolOutputSchema,
} from "@mako-ai/contracts";
import { z, type ZodTypeAny } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";
import { askTool } from "./ask/index.js";
import { agentFeedbackReportTool, agentFeedbackTool } from "./agent-feedback/index.js";
import { authPathTool, fileHealthTool, routeTraceTool, schemaUsageTool } from "./answers/index.js";
import {
  implementationHandoffArtifactTool,
  reviewBundleArtifactTool,
  taskPreflightArtifactTool,
  verificationBundleArtifactTool,
} from "./artifacts/index.js";
import {
  crossSearchTool,
  preflightTableTool,
  traceEdgeTool,
  traceErrorTool,
  traceFileTool,
  traceRpcTool,
  traceTableTool,
} from "./composers/index.js";
import {
  dbColumnsTool,
  dbFkTool,
  dbPingTool,
  dbRlsTool,
  dbRpcTool,
  dbTableSchemaTool,
} from "./db/index.js";
import { astFindPatternTool, biomeDiagnosticsTool, eslintDiagnosticsTool, gitPrecommitCheckTool, lintFilesTool, oxlintDiagnosticsTool, repoMapTool, typescriptDiagnosticsTool } from "./code-intel/index.js";
import { contextPacketTool } from "./context-packet/index.js";
import { liveTextSearchTool } from "./live-text-search/index.js";
import { projectIndexRefreshTool, projectIndexStatusTool } from "./project-index/index.js";
import {
  diagnosticRefreshTool,
  dbReviewCommentTool,
  dbReviewCommentsTool,
  dbReefRefreshTool,
  evidenceConfidenceTool,
  evidenceConflictsTool,
  fileFactsTool,
  fileFindingsTool,
  filePreflightTool,
  listReefRulesTool,
  projectConventionsTool,
  projectDiagnosticRunsTool,
  projectFactsTool,
  projectFindingsTool,
  projectOpenLoopsTool,
  reefDiffImpactTool,
  reefAgentStatusTool,
  reefInstructionsTool,
  reefKnownIssuesTool,
  reefOverlayDiffTool,
  reefInspectTool,
  reefScoutTool,
  reefWhereUsedTool,
  ruleMemoryTool,
  verificationStateTool,
  workingTreeOverlayTool,
} from "./reef/index.js";
import { extractRuleTemplateTool, rulePackValidateTool } from "./rule-packs/index.js";
import { findingAckBatchTool, findingAckTool, findingAcksReportTool } from "./finding-acks/index.js";
import { runtimeTelemetryReportTool } from "./runtime-telemetry/index.js";
import { recallAnswersTool, recallToolRunsTool } from "./session-recall/index.js";
import { rpcNeighborhoodTool, routeContextTool, tableNeighborhoodTool } from "./neighborhoods/index.js";
import { changePlanTool, flowMapTool, graphNeighborsTool, graphPathTool } from "./graph/index.js";
import { importsCyclesTool, importsDepsTool, importsHotspotsTool, importsImpactTool } from "./imports/index.js";
import { investigateTool, suggestTool } from "./investigation/index.js";
import { makoHelpTool } from "./mako-help/index.js";
import { tenantLeakAuditTool } from "./operators/index.js";
import { healthTrendTool, issuesNextTool, sessionHandoffTool } from "./project-intelligence/index.js";
import type { ToolServiceOptions } from "./runtime.js";
import { exportsOfTool, symbolsOfTool } from "./symbols/index.js";
import { toolBatchTool } from "./tool-batch/index.js";
import { toolAnnotations } from "./tool-operational-metadata.js";
import { workflowPacketTool } from "./workflow-packets/surfaces.js";

export interface MakoToolDefinition<Name extends string = ToolName> {
  name: Name;
  category: ToolDefinitionSummary["category"];
  description: string;
  annotations: ToolAnnotations;
  inputSchema: ZodTypeAny;
  outputSchema: ZodTypeAny;
  execute(input: ToolInput, options: ToolServiceOptions): Promise<unknown>;
}

export function schemaToJson(
  schema: ZodTypeAny,
  name: string,
  options: { useRootRefs?: boolean } = {},
): JsonObject {
  if (options.useRootRefs) {
    return zodToJsonSchema(schema, {
      name,
      $refStrategy: "root",
    }) as JsonObject;
  }

  return zodToJsonSchema(schema, {
    $refStrategy: "none",
  }) as JsonObject;
}

export function withToolHintsSchema(schema: ZodTypeAny): ZodTypeAny {
  if ((schema._def.typeName as string) === "ZodObject") {
    return (schema as z.AnyZodObject).extend(ToolHintsSchema.shape);
  }
  return z.intersection(schema, ToolHintsSchema);
}

export const TOOL_DEFINITIONS: readonly MakoToolDefinition[] = [
  {
    name: "task_preflight_artifact",
    category: "artifact",
    description: "Artifact tool for start-of-work preparation: compose implementation brief, verification plan, change plan, and flow map into one typed preflight artifact. Basis is stable — identical inputs produce the same artifactId, so callers may dedupe on it.",
    annotations: toolAnnotations("task_preflight_artifact"),
    inputSchema: TaskPreflightArtifactToolInputSchema,
    outputSchema: TaskPreflightArtifactToolOutputSchema,
    execute: (input, options) => taskPreflightArtifactTool(input as never, options),
  },
  {
    name: "implementation_handoff_artifact",
    category: "artifact",
    description: "Artifact tool for reusable implementation handoff: compose one implementation brief and the current session handoff into a typed handoff artifact. Basis is session-scoped — session_handoff shifts with every tool call, so artifactId moves between calls by design (each call captures the current session state). Do not dedupe on artifactId.",
    annotations: toolAnnotations("implementation_handoff_artifact"),
    inputSchema: ImplementationHandoffArtifactToolInputSchema,
    outputSchema: ImplementationHandoffArtifactToolOutputSchema,
    execute: (input, options) => implementationHandoffArtifactTool(input as never, options),
  },
  {
    name: "review_bundle_artifact",
    category: "artifact",
    description: "Artifact tool for reviewer-facing change inspection: compose implementation brief, change plan, optional flow map, and optional tenant audit into one typed review bundle. Basis is stable — identical inputs produce the same artifactId, so callers may dedupe on it.",
    annotations: toolAnnotations("review_bundle_artifact"),
    inputSchema: ReviewBundleArtifactToolInputSchema,
    outputSchema: ReviewBundleArtifactToolOutputSchema,
    execute: (input, options) => reviewBundleArtifactTool(input as never, options),
  },
  {
    name: "verification_bundle_artifact",
    category: "artifact",
    description: "Artifact tool for safe completion and verification: compose verification plan, project-intelligence signals, and optional tenant audit into one typed verification bundle. Basis is stable by default; artifactId shifts across calls only when `includeSessionHandoff` or `includeIssuesNext` is set, because those inputs are session-scoped. Dedupe is safe when both flags are off.",
    annotations: toolAnnotations("verification_bundle_artifact"),
    inputSchema: VerificationBundleArtifactToolInputSchema,
    outputSchema: VerificationBundleArtifactToolOutputSchema,
    execute: (input, options) => verificationBundleArtifactTool(input as never, options),
  },
  {
    name: "suggest",
    category: "workflow",
    description: "Workflow tool for tool-chain recommendations: choose one canonical workflow or a short ordered sequence without executing hidden planner logic.",
    annotations: toolAnnotations("suggest"),
    inputSchema: SuggestToolInputSchema,
    outputSchema: SuggestToolOutputSchema,
    execute: (input, options) => suggestTool(input as never, options),
  },
  {
    name: "investigate",
    category: "workflow",
    description: "Workflow tool for bounded read-only investigation: run a short sequential tool chain over shipped workflows and return typed step history.",
    annotations: toolAnnotations("investigate"),
    inputSchema: InvestigateToolInputSchema,
    outputSchema: InvestigateToolOutputSchema,
    execute: (input, options) => investigateTool(input as never, options),
  },
  {
    name: "graph_neighbors",
    category: "graph",
    description: "Graph tool for adjacency questions: traverse outward from one or more start entities with explicit direction, depth, and edge filters.",
    annotations: toolAnnotations("graph_neighbors"),
    inputSchema: GraphNeighborsToolInputSchema,
    outputSchema: GraphNeighborsToolOutputSchema,
    execute: (input, options) => graphNeighborsTool(input as never, options),
  },
  {
    name: "graph_path",
    category: "graph",
    description: "Graph tool for connection questions: find one shortest typed path between two entities while keeping heuristic edges explicit and opt-in.",
    annotations: toolAnnotations("graph_path"),
    inputSchema: GraphPathToolInputSchema,
    outputSchema: GraphPathToolOutputSchema,
    execute: (input, options) => graphPathTool(input as never, options),
  },
  {
    name: "flow_map",
    category: "graph",
    description: "Graph tool for end-to-end flow questions: turn one graph path into ordered flow steps, transitions, and major boundary crossings.",
    annotations: toolAnnotations("flow_map"),
    inputSchema: FlowMapToolInputSchema,
    outputSchema: FlowMapToolOutputSchema,
    execute: (input, options) => flowMapTool(input as never, options),
  },
  {
    name: "change_plan",
    category: "graph",
    description: "Graph tool for bounded change scope: return path-derived direct surfaces, one-hop dependent surfaces, and an explicit dependency order.",
    annotations: toolAnnotations("change_plan"),
    inputSchema: ChangePlanToolInputSchema,
    outputSchema: ChangePlanToolOutputSchema,
    execute: (input, options) => changePlanTool(input as never, options),
  },
  {
    name: "tenant_leak_audit",
    category: "operator",
    description: "Operator tool for tenant-boundary review: audit tenant-keyed tables, RLS posture, and RPC/code touch points without making generic security-score claims.",
    annotations: toolAnnotations("tenant_leak_audit"),
    inputSchema: TenantLeakAuditToolInputSchema,
    outputSchema: TenantLeakAuditToolOutputSchema,
    execute: (input, options) => tenantLeakAuditTool(input as never, options),
  },
  {
    name: "session_handoff",
    category: "operator",
    description: "Operator tool for derived project-state handoff: summarize recent answer traces, active unresolved focus, and recorded follow-up momentum.",
    annotations: toolAnnotations("session_handoff"),
    inputSchema: SessionHandoffToolInputSchema,
    outputSchema: SessionHandoffToolOutputSchema,
    execute: (input, options) => sessionHandoffTool(input as never, options),
  },
  {
    name: "recall_answers",
    category: "session_recall",
    description: "Read-only session-recall tool: search prior project answer traces by text, query kind, support level, trust state, and ISO time window. Returns bounded answer summaries, pre-cap matchCount, truncation signal, and optional stored answer markdown. Does not run the answer loop or infer freshness.",
    annotations: toolAnnotations("recall_answers"),
    inputSchema: RecallAnswersToolInputSchema,
    outputSchema: RecallAnswersToolOutputSchema,
    execute: (input, options) => recallAnswersTool(input as never, options),
  },
  {
    name: "recall_tool_runs",
    category: "session_recall",
    description: "Read-only session-recall tool: inspect prior project tool_runs by tool name, outcome, request id, and ISO time window. Returns bounded summaries with runId plus requestId when available; use requestId as agent_feedback.referencedRequestId. Default limit is 50, max 500. Persisted payloads are only included when includePayload is true.",
    annotations: toolAnnotations("recall_tool_runs"),
    inputSchema: RecallToolRunsToolInputSchema,
    outputSchema: RecallToolRunsToolOutputSchema,
    execute: (input, options) => recallToolRunsTool(input as never, options),
  },
  {
    name: "table_neighborhood",
    category: "neighborhood",
    description: "Neighborhood composer for one table: combines db_table_schema/db_rls-equivalent schema snapshot data, schema_usage read/write sites, trace_table RPC-to-table edges, and route_trace handler routes into one bounded typed bundle.",
    annotations: toolAnnotations("table_neighborhood"),
    inputSchema: TableNeighborhoodToolInputSchema,
    outputSchema: TableNeighborhoodToolOutputSchema,
    execute: (input, options) => tableNeighborhoodTool(input as never, options),
  },
  {
    name: "route_context",
    category: "neighborhood",
    description: "Neighborhood composer for one route: combines route_trace route resolution, file_health handler summary, imports_deps direct imports/dependents, schema_usage touches, trace_rpc downstream table edges, and db_rls policy surfaces.",
    annotations: toolAnnotations("route_context"),
    inputSchema: RouteContextToolInputSchema,
    outputSchema: RouteContextToolOutputSchema,
    execute: (input, options) => routeContextTool(input as never, options),
  },
  {
    name: "rpc_neighborhood",
    category: "neighborhood",
    description: "Neighborhood composer for one RPC: combines db_rpc-equivalent schema snapshot signature/body, schema_usage app-code callers, trace_rpc function-to-table refs, and db_rls policies on touched tables into one bounded bundle.",
    annotations: toolAnnotations("rpc_neighborhood"),
    inputSchema: RpcNeighborhoodToolInputSchema,
    outputSchema: RpcNeighborhoodToolOutputSchema,
    execute: (input, options) => rpcNeighborhoodTool(input as never, options),
  },
  {
    name: "agent_feedback",
    category: "feedback",
    description: "Append-only feedback tool for rating a prior Mako tool run from the agent perspective. Use sparingly when a result was notably good, notably bad, or wrong; do not emit routine feedback after every call. Requires referencedToolName and referencedRequestId so each row is tied to a specific prior run. Grade semantics: full = helped complete the task, partial = somewhat useful but flawed, no = wrong or wasted the turn. Starter reason codes: full: answer_complete, evidence_sufficient, trust_matches; partial: partial_coverage, noisy, stale_evidence, missing_known_caller, top_not_useful; no: answer_wrong, wasted_turn, tool_did_nothing, schema_missing.",
    annotations: toolAnnotations("agent_feedback"),
    inputSchema: AgentFeedbackToolInputSchema,
    outputSchema: AgentFeedbackToolOutputSchema,
    execute: (input, options) => agentFeedbackTool(input as never, options),
  },
  {
    name: "agent_feedback_report",
    category: "feedback",
    description: "Read-only inspection over agent_feedback rows in mako_usefulness_events: return grade counts by referenced tool plus bounded recent entries, filterable by referencedToolName, grade, and ISO time window. Use to review which tools agents found helpful, noisy, wrong, or incomplete.",
    annotations: toolAnnotations("agent_feedback_report"),
    inputSchema: AgentFeedbackReportToolInputSchema,
    outputSchema: AgentFeedbackReportToolOutputSchema,
    execute: (input, options) => agentFeedbackReportTool(input as never, options),
  },
  {
    name: "health_trend",
    category: "operator",
    description: "Operator tool for project-state trend review: compare a recent trace window against a prior window without fabricating trend lines when history is thin.",
    annotations: toolAnnotations("health_trend"),
    inputSchema: HealthTrendToolInputSchema,
    outputSchema: HealthTrendToolOutputSchema,
    execute: (input, options) => healthTrendTool(input as never, options),
  },
  {
    name: "issues_next",
    category: "operator",
    description: "Operator tool for queue-oriented recommendations: derive one current issue plus queued follow-on issues from recent unresolved project traces.",
    annotations: toolAnnotations("issues_next"),
    inputSchema: IssuesNextToolInputSchema,
    outputSchema: IssuesNextToolOutputSchema,
    execute: (input, options) => issuesNextTool(input as never, options),
  },
  {
    name: "route_trace",
    category: "answer",
    description: "Answer tool for route questions: trace a route to the indexed handler, matching files, and nearby evidence.",
    annotations: toolAnnotations("route_trace"),
    inputSchema: RouteTraceToolInputSchema,
    outputSchema: RouteTraceToolOutputSchema,
    execute: (input, options) => routeTraceTool(input as never, options),
  },
  {
    name: "schema_usage",
    category: "answer",
    description: "Answer tool for schema questions: find where an indexed schema object is defined and directly referenced in app code. RPC-mediated touches are intentionally excluded; use trace_rpc, route_context, table_neighborhood, or flow_map for transitive schema paths.",
    annotations: toolAnnotations("schema_usage"),
    inputSchema: SchemaUsageToolInputSchema,
    outputSchema: SchemaUsageToolOutputSchema,
    execute: (input, options) => schemaUsageTool(input as never, options),
  },
  {
    name: "file_health",
    category: "answer",
    description: "Answer tool for file questions: summarize a file's role, dependents, and notable risks with evidence.",
    annotations: toolAnnotations("file_health"),
    inputSchema: FileHealthToolInputSchema,
    outputSchema: FileHealthToolOutputSchema,
    execute: (input, options) => fileHealthTool(input as never, options),
  },
  {
    name: "auth_path",
    category: "answer",
    description: "Answer tool for auth questions: trace likely auth boundaries for a route, file, or feature without overclaiming.",
    annotations: toolAnnotations("auth_path"),
    inputSchema: AuthPathToolInputSchema,
    outputSchema: AuthPathToolOutputSchema,
    execute: (input, options) => authPathTool(input as never, options),
  },
  {
    name: "imports_deps",
    category: "imports",
    description: "Imports tool for direct dependencies: list a file's indexed imports and flag unresolved internal edges.",
    annotations: toolAnnotations("imports_deps"),
    inputSchema: ImportsDepsToolInputSchema,
    outputSchema: ImportsDepsToolOutputSchema,
    execute: (input, options) => importsDepsTool(input as never, options),
  },
  {
    name: "imports_impact",
    category: "imports",
    description: "Imports tool for downstream impact: trace which indexed files depend on a file through the import graph.",
    annotations: toolAnnotations("imports_impact"),
    inputSchema: ImportsImpactToolInputSchema,
    outputSchema: ImportsImpactToolOutputSchema,
    execute: (input, options) => importsImpactTool(input as never, options),
  },
  {
    name: "imports_hotspots",
    category: "imports",
    description: "Imports tool for graph hotspots: rank the most connected files in the indexed internal import graph.",
    annotations: toolAnnotations("imports_hotspots"),
    inputSchema: ImportsHotspotsToolInputSchema,
    outputSchema: ImportsHotspotsToolOutputSchema,
    execute: (input, options) => importsHotspotsTool(input as never, options),
  },
  {
    name: "imports_cycles",
    category: "imports",
    description: "Imports tool for cycle detection: detect circular dependencies in the indexed internal import graph.",
    annotations: toolAnnotations("imports_cycles"),
    inputSchema: ImportsCyclesToolInputSchema,
    outputSchema: ImportsCyclesToolOutputSchema,
    execute: (input, options) => importsCyclesTool(input as never, options),
  },
  {
    name: "symbols_of",
    category: "symbols",
    description: "Symbols tool for declarations: list the indexed symbols declared in a file.",
    annotations: toolAnnotations("symbols_of"),
    inputSchema: SymbolsOfToolInputSchema,
    outputSchema: SymbolsOfToolOutputSchema,
    execute: (input, options) => symbolsOfTool(input as never, options),
  },
  {
    name: "exports_of",
    category: "symbols",
    description: "Symbols tool for exports: list only the indexed symbols that a file exports.",
    annotations: toolAnnotations("exports_of"),
    inputSchema: ExportsOfToolInputSchema,
    outputSchema: ExportsOfToolOutputSchema,
    execute: (input, options) => exportsOfTool(input as never, options),
  },
  {
    name: "mako_help",
    category: "context",
    description: "Orientation tool for coding agents: given a natural-language task, return the recommended Mako workflow recipe as an ordered tool sequence with pre-filled suggestedArgs, batchable follow-ups, and notes. Use before reading long AGENTS/CLAUDE docs when deciding whether to start with context_packet, cross_search, file_preflight, lint_files, verification_state, or DB/Reef tools. Read-only and does not execute the returned steps.",
    annotations: toolAnnotations("mako_help"),
    inputSchema: MakoHelpToolInputSchema,
    outputSchema: MakoHelpToolOutputSchema,
    execute: (input) => makoHelpTool(input as never),
  },
  {
    name: "ask",
    category: "router",
    description: "Router tool: map one natural-language engineering question to one canonical named tool, or conservatively fall back to free_form.",
    annotations: toolAnnotations("ask"),
    inputSchema: AskToolInputSchema,
    outputSchema: AskToolOutputSchema,
    execute: (input, options) => askTool(input as never, options),
  },
  {
    name: "workflow_packet",
    category: "workflow",
    description: "Workflow tool: generate a typed workflow packet from a project-scoped query answer and expose watch/surface metadata.",
    annotations: toolAnnotations("workflow_packet"),
    inputSchema: WorkflowPacketToolInputSchema,
    outputSchema: WorkflowPacketToolOutputSchema,
    execute: (input, options) => workflowPacketTool(input as never, options),
  },
  {
    name: "ast_find_pattern",
    category: "code_intel",
    description: "Code-intelligence tool for structural pattern search: run one ast-grep pattern against every fresh indexed TypeScript / TSX / JavaScript / JSX file and return typed matches (file, line range, column range, matched text, captured metavariables). Ambiguous TSX/JSX snippets that start with `{`, `[`, or `<` retry with an auto-anchored `const _ = ...` parser context when the original pattern returns zero matches, and `patternAttempts` / match `patternVariant` report which form matched. Reef-backed freshness guard skips stale/deleted/unknown indexed files so old AST rows do not become phantom matches; set MAKO_REEF_BACKED=legacy for the one-release rollback path. Read-only; never edits files. Use when text/FTS search is too noisy for structural queries (e.g. `console.log($X)`, `await supabase.rpc($NAME)`, `useEffect($FN, [])`).",
    annotations: toolAnnotations("ast_find_pattern"),
    inputSchema: AstFindPatternToolInputSchema,
    outputSchema: AstFindPatternToolOutputSchema,
    execute: (input, options) => astFindPatternTool(input as never, options),
  },
  {
    name: "live_text_search",
    category: "code_intel",
    description: "Code-intelligence tool for live filesystem text search: run ripgrep over the attached project root and return bounded file/line matches. Defaults to fixed-string matching; pass fixedStrings: false to use ripgrep regex syntax. Read-only and explicitly live, so use it when the indexed snapshot may be stale or when exact text search is the right primitive.",
    annotations: toolAnnotations("live_text_search"),
    inputSchema: LiveTextSearchToolInputSchema,
    outputSchema: LiveTextSearchToolOutputSchema,
    execute: (input, options) => liveTextSearchTool(input as never, options),
  },
  {
    name: "lint_files",
    category: "code_intel",
    description: "Code-intelligence tool for diagnostics on an indexed file set: run rule-packs, including canonicalHelper producer/consumer checks, plus TS-aware and structural alignment diagnostics; persist indexed Reef findings/run metadata under source `lint_files`; and return typed AnswerSurfaceIssue findings. Same engine that powers the answer loop and review_bundle, so findings stay consistent across surfaces.",
    annotations: toolAnnotations("lint_files"),
    inputSchema: LintFilesToolInputSchema,
    outputSchema: LintFilesToolOutputSchema,
    execute: (input, options) => lintFilesTool(input as never, options),
  },
  {
    name: "typescript_diagnostics",
    category: "code_intel",
    description: "Explicit Reef ingestion tool for semantic TypeScript compiler diagnostics: read tsconfig, run the TypeScript program with no emit, persist working-tree ProjectFinding rows under source `typescript`, and return bounded findings. This may run a broad typecheck; use diagnostic_refresh with `typescript_syntax` for syntax-only refresh.",
    annotations: toolAnnotations("typescript_diagnostics"),
    inputSchema: TypeScriptDiagnosticsToolInputSchema,
    outputSchema: TypeScriptDiagnosticsToolOutputSchema,
    execute: (input, options) => typescriptDiagnosticsTool(input as never, options),
  },
  {
    name: "eslint_diagnostics",
    category: "code_intel",
    description: "Explicit Reef ingestion tool for ESLint diagnostics: run the project's local ESLint executable on the requested project-relative files with JSON output, persist working-tree ProjectFinding rows under source `eslint`, and record unavailable/error/succeeded run status. File-mode only; does not run broad project lint.",
    annotations: toolAnnotations("eslint_diagnostics"),
    inputSchema: EslintDiagnosticsToolInputSchema,
    outputSchema: EslintDiagnosticsToolOutputSchema,
    execute: (input, options) => eslintDiagnosticsTool(input as never, options),
  },
  {
    name: "oxlint_diagnostics",
    category: "code_intel",
    description: "Explicit Reef ingestion tool for Oxlint diagnostics: run the project's local Oxlint executable or JSON package script on requested project-relative files with `--format json`, persist working-tree ProjectFinding rows under source `oxlint`, and record unavailable/error/succeeded run status. File-mode only; does not run broad project lint.",
    annotations: toolAnnotations("oxlint_diagnostics"),
    inputSchema: OxlintDiagnosticsToolInputSchema,
    outputSchema: OxlintDiagnosticsToolOutputSchema,
    execute: (input, options) => oxlintDiagnosticsTool(input as never, options),
  },
  {
    name: "biome_diagnostics",
    category: "code_intel",
    description: "Explicit Reef ingestion tool for Biome diagnostics: run the project's local Biome executable or GitLab-reporter package script on requested project-relative files with `check --reporter=gitlab`, persist working-tree ProjectFinding rows under source `biome`, and record unavailable/error/succeeded run status. File-mode only; deliberately avoids Biome's experimental JSON reporter.",
    annotations: toolAnnotations("biome_diagnostics"),
    inputSchema: BiomeDiagnosticsToolInputSchema,
    outputSchema: BiomeDiagnosticsToolOutputSchema,
    execute: (input, options) => biomeDiagnosticsTool(input as never, options),
  },
  {
    name: "git_precommit_check",
    category: "code_intel",
    description: "Git pre-commit guard for staged TS/TSX files: reads staged blobs, checks API route auth guards and Next.js server/client boundary mistakes, persists staged Reef findings unless MAKO_REEF_BACKED disables the migration, and returns hook-friendly continue/stopReason output. Uses discovered project-profile auth guards/server-only modules plus optional .mako/git-guard.json/input allowlists. Never edits the index or worktree.",
    annotations: toolAnnotations("git_precommit_check"),
    inputSchema: GitPrecommitCheckToolInputSchema,
    outputSchema: GitPrecommitCheckToolOutputSchema,
    execute: (input, options) => gitPrecommitCheckTool(input as never, options),
  },
  {
    name: "diagnostic_refresh",
    category: "code_intel",
    description: "Explicit Reef diagnostic ingestion runner: invoke selected diagnostic sources (lint_files, programmatic_findings, typescript_syntax, TypeScript, ESLint, Oxlint, Biome, or git_precommit_check), persist their Reef diagnostic runs/findings through the underlying tools, and return a compact per-source summary. File-mode sources are skipped unless files are supplied; this is a mutation tool because it refreshes Reef state.",
    annotations: toolAnnotations("diagnostic_refresh"),
    inputSchema: DiagnosticRefreshToolInputSchema,
    outputSchema: DiagnosticRefreshToolOutputSchema,
    execute: (input, options) => diagnosticRefreshTool(input as never, options),
  },
  {
    name: "db_reef_refresh",
    category: "project",
    description: "Explicit Reef DB ingestion tool: replace indexed Reef facts for the current schema snapshot, including schemas, tables, columns, indexes, foreign keys, RLS policies, triggers, enums, RPCs, RPC-to-table refs, and indexed schema usages. Uses the existing schema snapshot/read-model indexes; run project_index_refresh first if the snapshot is stale or missing.",
    annotations: toolAnnotations("db_reef_refresh"),
    inputSchema: DbReefRefreshToolInputSchema,
    outputSchema: DbReefRefreshToolOutputSchema,
    execute: (input, options) => dbReefRefreshTool(input as never, options),
  },
  {
    name: "db_review_comment",
    category: "project",
    description: "Append-only DB review note tool: leave a short AI/operator comment on a database object such as a table, column, policy, trigger, publication, replication slot, or general replication topic. Writes only to Mako's local project store; it never mutates the live database.",
    annotations: toolAnnotations("db_review_comment"),
    inputSchema: DbReviewCommentToolInputSchema,
    outputSchema: DbReviewCommentToolOutputSchema,
    execute: (input, options) => dbReviewCommentTool(input as never, options),
  },
  {
    name: "db_review_comments",
    category: "project",
    description: "Read DB review comments from Mako's local append-only ledger, filterable by database object, category, tag, free-text query, or target fingerprint. Use during schema/table/RLS/replication review to recover prior AI/operator notes.",
    annotations: toolAnnotations("db_review_comments"),
    inputSchema: DbReviewCommentsToolInputSchema,
    outputSchema: DbReviewCommentsToolOutputSchema,
    execute: (input, options) => dbReviewCommentsTool(input as never, options),
  },
  {
    name: "repo_map",
    category: "code_intel",
    description: "Code-intelligence tool for repo orientation: emit a token-budgeted aider-style outline of the indexed project (ranked files + key symbols) as first-turn context for agents meeting an unfamiliar codebase. Ranking approximates centrality via `fanIn * 2 + fanOut + 0.1`; symbol selection prefers exported declarations. Read-only; default budget 1024 tokens (char/4 approximation), cap 16384.",
    annotations: toolAnnotations("repo_map"),
    inputSchema: RepoMapToolInputSchema,
    outputSchema: RepoMapToolOutputSchema,
    execute: (input, options) => repoMapTool(input as never, options),
  },
  {
    name: "context_packet",
    category: "context",
    description: "Context scout for coding agents: turn a messy request into ranked, source-labeled, readable context using deterministic providers first (files, routes, symbols, schema, import graph, centrality, hot hints). Reef-backed enrichments add working-tree overlay metadata and active findings; use risksMinConfidence to suppress low-confidence risk speculation. Set MAKO_REEF_BACKED=legacy for the one-release rollback path. Read-only; does not refresh the index. Use as the first-mile packet before normal harness read/search/edit loops.",
    annotations: toolAnnotations("context_packet"),
    inputSchema: ContextPacketToolInputSchema,
    outputSchema: ContextPacketToolOutputSchema,
    execute: (input, options) => contextPacketTool(input as never, options),
  },
  {
    name: "tool_batch",
    category: "context",
    description: "Read-only batching wrapper for independent Mako lookups. The input schema only accepts batchable read-only tools; runtime also rejects mutation tools and recursive tool_batch calls defensively. Returns labeled sub-results with per-op duration. Use `verbosity: \"compact\"` or per-op `resultMode: \"summary\"` to return compact summaries instead of full payloads; per-op `resultMode: \"full\"` keeps the full output. Each sub-op's `projectId` is overridden with the parent batch's resolved project, so all ops run against one project. Use to reduce round-trips after a context_packet recommends several expansions.",
    annotations: toolAnnotations("tool_batch"),
    inputSchema: ToolBatchInputSchema,
    outputSchema: ToolBatchToolOutputSchema,
    execute: (input, options) => toolBatchTool(input as never, options),
  },
  {
    name: "project_index_status",
    category: "project",
    description: "Project tool for index freshness: compare indexed file rows against live disk metadata, report Reef working-tree fact freshness, watch state, latest index run, unindexedScan status, and a suggested next action. By default this checks indexed rows only and reports that the new-file scan was skipped; pass includeUnindexed: true to pay the repo walk cost and get an exact count/details for files not yet in the index. Trust/stability is not freshness; this tool answers whether the index snapshot is current.",
    annotations: toolAnnotations("project_index_status"),
    inputSchema: ProjectIndexStatusToolInputSchema,
    outputSchema: ProjectIndexStatusToolOutputSchema,
    execute: (input, options) => projectIndexStatusTool(input as never, options),
  },
  {
    name: "project_index_refresh",
    category: "project",
    description: "Mutation tool for index freshness: run the project indexer through the current project-store cache when the snapshot is stale, unknown, deleted, or has unindexed files, then return before/after freshness summaries and the new index run. In if_stale mode, unknown freshness refreshes defensively and unindexed files count as stale work.",
    annotations: toolAnnotations("project_index_refresh"),
    inputSchema: ProjectIndexRefreshToolInputSchema,
    outputSchema: ProjectIndexRefreshToolOutputSchema,
    execute: (input, options) => projectIndexRefreshTool(input as never, options),
  },
  {
    name: "runtime_telemetry_report",
    category: "runtime_telemetry",
    description: "Read-only inspection over mako_usefulness_events (Phase 8.1): return aggregate counts (by decisionKind, by family, by grade) and a bounded list of recent events, filterable by decisionKind, family, requestId, and ISO time window. Use to verify usefulness capture is flowing or to triage why a decision site emitted the grade it did. Never writes to the event table.",
    annotations: toolAnnotations("runtime_telemetry_report"),
    inputSchema: RuntimeTelemetryReportToolInputSchema,
    outputSchema: RuntimeTelemetryReportToolOutputSchema,
    execute: (input, options) => runtimeTelemetryReportTool(input as never, options),
  },
  {
    name: "finding_ack",
    category: "finding_acks",
    description: "Mutation tool for verified-safe markers: append one row to the finding_acks ledger so subsequent ast_find_pattern / lint_files callers that opt into the same category filter the match out. Category is caller-owned (for lint findings, finding.code is the recommended default). For ast_find_pattern matches, pass `match.ackableFingerprint`; for lint_files findings, pass `finding.identity.matchBasedId`. Append-only; duplicate (projectId, category, fingerprint) inserts persist as separate rows and dedupe at query time. Emits one RuntimeUsefulnessEvent per successful call.",
    annotations: toolAnnotations("finding_ack"),
    inputSchema: FindingAckToolInputSchema,
    outputSchema: FindingAckToolOutputSchema,
    execute: (input, options) => findingAckTool(input as never, options),
  },
  {
    name: "finding_ack_batch",
    category: "finding_acks",
    description: "Mutation batch for reviewed finding acknowledgements: append many finding_acks rows in one call while sharing batch-level defaults for category, subjectKind, status, reason, acknowledgedBy, sourceToolName, and sourceRuleId. Use when a scan returns many reviewed false positives or accepted tradeoffs. Emits one finding_ack telemetry event per successful row.",
    annotations: toolAnnotations("finding_ack_batch"),
    inputSchema: FindingAckBatchToolInputSchema,
    outputSchema: FindingAckBatchToolOutputSchema,
    execute: (input, options) => findingAckBatchTool(input as never, options),
  },
  {
    name: "finding_acks_report",
    category: "finding_acks",
    description: "Read-only inspection over the finding_acks ledger: return aggregate counts (by category, status, subjectKind, filePath) and a bounded reverse-chronological list of acks, filterable by category, subjectKind, filePath, status, and ISO time window. Use to see what operators have suppressed and which categories carry the most weight. Never writes to the ledger.",
    annotations: toolAnnotations("finding_acks_report"),
    inputSchema: FindingAcksReportToolInputSchema,
    outputSchema: FindingAcksReportToolOutputSchema,
    execute: (input, options) => findingAcksReportTool(input as never, options),
  },
  {
    name: "project_findings",
    category: "project",
    description: "Reef read tool for active project findings: query the durable Reef findings view by overlay, source, status, and resolved inclusion. The source filter accepts a producer source, bare rule ID, or rule_pack:<ruleId>. Acknowledged status is derived from the existing finding_ack ledger, so this is the canonical read path for Reef-native lint/rule findings.",
    annotations: toolAnnotations("project_findings"),
    inputSchema: ProjectFindingsToolInputSchema,
    outputSchema: ProjectFindingsToolOutputSchema,
    execute: (input, options) => projectFindingsTool(input as never, options),
  },
  {
    name: "file_findings",
    category: "project",
    description: "Reef read tool for one project-relative file: return durable Reef findings attached to that file, with the same overlay/source/status filters as project_findings, including source aliases for bare rule IDs and rule_pack:<ruleId>. Use this before editing a file when a shell or agent needs known active diagnostics without rerunning broad lint.",
    annotations: toolAnnotations("file_findings"),
    inputSchema: FileFindingsToolInputSchema,
    outputSchema: FileFindingsToolOutputSchema,
    execute: (input, options) => fileFindingsTool(input as never, options),
  },
  {
    name: "file_preflight",
    category: "project",
    description: "Reef pre-edit composer for one file: returns durable findings, file-scoped diagnostic freshness, source-filtered recent runs, watcher diagnostic state, applicable conventions, and finding acknowledgement history in one read-only packet. Use before editing a file when an agent needs the operational gate without separate file_findings, verification_state, project_conventions, and finding_acks_report calls.",
    annotations: toolAnnotations("file_preflight"),
    inputSchema: FilePreflightToolInputSchema,
    outputSchema: FilePreflightToolOutputSchema,
    execute: (input, options) => filePreflightTool(input as never, options),
  },
  {
    name: "project_facts",
    category: "project",
    description: "Reef read tool for durable project facts: query facts by overlay, source, kind, and subject fingerprint. Use this when an agent or shell needs the calculated substrate behind findings without rerunning analysis.",
    annotations: toolAnnotations("project_facts"),
    inputSchema: ProjectFactsToolInputSchema,
    outputSchema: ProjectFactsToolOutputSchema,
    execute: (input, options) => projectFactsTool(input as never, options),
  },
  {
    name: "file_facts",
    category: "project",
    description: "Reef read tool for one file's durable facts: computes the file subject fingerprint and returns facts such as working_tree_overlay file_snapshot rows. Use this to inspect what Reef currently knows about a file across overlays.",
    annotations: toolAnnotations("file_facts"),
    inputSchema: FileFactsToolInputSchema,
    outputSchema: FileFactsToolOutputSchema,
    execute: (input, options) => fileFactsTool(input as never, options),
  },
  {
    name: "working_tree_overlay",
    category: "project",
    description: "Advisory Reef mutation: snapshot working-tree file facts for explicit files, watcher-dirty paths, or non-fresh indexed paths. Persists file_snapshot facts with size, mtime, line count, sha256, or deleted state; it does not reparse AST, imports, routes, or schema.",
    annotations: toolAnnotations("working_tree_overlay"),
    inputSchema: WorkingTreeOverlayToolInputSchema,
    outputSchema: WorkingTreeOverlayToolOutputSchema,
    execute: (input, options) => workingTreeOverlayTool(input as never, options),
  },
  {
    name: "reef_overlay_diff",
    category: "project",
    description: "Reef read tool for overlay comparison: diff durable facts between two overlays, defaulting indexed vs working_tree, with optional filePath/kind/source filters. Use after working_tree_overlay or before edits to see exactly what Reef believes changed without rerunning diagnostics.",
    annotations: toolAnnotations("reef_overlay_diff"),
    inputSchema: ReefOverlayDiffToolInputSchema,
    outputSchema: ReefOverlayDiffToolOutputSchema,
    execute: (input, options) => reefOverlayDiffTool(input as never, options),
  },
  {
    name: "reef_diff_impact",
    category: "context",
    description: "Reef mid-edit impact composer: for changed working-tree files, return affected import callers, active caller findings that may need re-checking, and conventions the diff or impacted callers may violate. Reads existing working_tree_overlay facts and import graph state; it does not refresh or mutate Reef.",
    annotations: toolAnnotations("reef_diff_impact"),
    inputSchema: ReefDiffImpactToolInputSchema,
    outputSchema: ReefDiffImpactToolOutputSchema,
    execute: (input, options) => reefDiffImpactTool(input as never, options),
  },
  {
    name: "reef_instructions",
    category: "project",
    description: "Reef read tool for scoped project instructions: load .mako/instructions.md and applicable AGENTS.md files for requested project-relative files, returning structured instruction items plus derived Reef fact shapes. Reads only inside the project root and does not persist facts.",
    annotations: toolAnnotations("reef_instructions"),
    inputSchema: ReefInstructionsToolInputSchema,
    outputSchema: ReefInstructionsToolOutputSchema,
    execute: (input, options) => reefInstructionsTool(input as never, options),
  },
  {
    name: "list_reef_rules",
    category: "project",
    description: "Reef read tool for rule metadata: list durable rule descriptors, optionally filtered by source namespace or enabled-by-default status. Descriptors explain which facts a finding source consumes and what rule ids mean.",
    annotations: toolAnnotations("list_reef_rules"),
    inputSchema: ListReefRulesToolInputSchema,
    outputSchema: ListReefRulesToolOutputSchema,
    execute: (input, options) => listReefRulesTool(input as never, options),
  },
  {
    name: "rule_pack_validate",
    category: "project",
    description: "Read-only Reef rule-pack authoring tool: validate .mako/rules YAML packs, including canonicalHelper cross-file declarations; return pack/rule counts, schema errors, and optional ReefRuleDescriptor previews without running diagnostics or writing Reef state.",
    annotations: toolAnnotations("rule_pack_validate"),
    inputSchema: RulePackValidateToolInputSchema,
    outputSchema: RulePackValidateToolOutputSchema,
    execute: (input, options) => rulePackValidateTool(input as never, options),
  },
  {
    name: "extract_rule_template",
    category: "project",
    description: "Read-only Reef rule-pack mining tool: inspect a local git fix diff and propose .mako/rules YAML templates from removed TS/JS anti-pattern shapes, with related durable findings when available. Does not write files or mutate Reef state.",
    annotations: toolAnnotations("extract_rule_template"),
    inputSchema: ExtractRuleTemplateToolInputSchema,
    outputSchema: ExtractRuleTemplateToolOutputSchema,
    execute: (input, options) => extractRuleTemplateTool(input as never, options),
  },
  {
    name: "project_diagnostic_runs",
    category: "project",
    description: "Reef read tool for diagnostic source runs: list recent lint/type adapter runs by source and status, including unavailable/error/succeeded state, duration, counts, command, config, cwd, metadata, and derived cache freshness/age. Use this to distinguish no findings from a diagnostic source that did not run or ran too long ago.",
    annotations: toolAnnotations("project_diagnostic_runs"),
    inputSchema: ProjectDiagnosticRunsToolInputSchema,
    outputSchema: ProjectDiagnosticRunsToolOutputSchema,
    execute: (input, options) => projectDiagnosticRunsTool(input as never, options),
  },
  {
    name: "reef_scout",
    category: "context",
    description: "Reef 7 model-facing scout view: turn a messy request into intent-weighted, explainable candidates from durable Reef facts, findings, rules, and diagnostic runs. App-flow queries prefer files/routes/findings; RLS/schema queries prefer database evidence. This is a context scout, not an editing agent; use normal harness read/search after the packet.",
    annotations: toolAnnotations("reef_scout"),
    inputSchema: ReefScoutToolInputSchema,
    outputSchema: ReefScoutToolOutputSchema,
    execute: (input, options) => reefScoutTool(input as never, options),
  },
  {
    name: "reef_inspect",
    category: "context",
    description: "Reef 7 inspection view: explain one file or subject fingerprint by returning its durable facts, findings, and relevant diagnostic runs. Use after reef_scout when the model needs the evidence trail and freshness details before editing.",
    annotations: toolAnnotations("reef_inspect"),
    inputSchema: ReefInspectToolInputSchema,
    outputSchema: ReefInspectToolOutputSchema,
    execute: (input, options) => reefInspectTool(input as never, options),
  },
  {
    name: "reef_where_used",
    category: "context",
    description: "Reef maintained structural query: answer where a symbol, component, route, file, or indexed pattern is defined and used from maintained symbols/imports/routes first. Does not run grep; returns a fallback recommendation when maintained state has no answer.",
    annotations: toolAnnotations("reef_where_used"),
    inputSchema: ReefWhereUsedToolInputSchema,
    outputSchema: ReefWhereUsedToolOutputSchema,
    execute: (input, options) => reefWhereUsedTool(input as never, options),
  },
  {
    name: "project_open_loops",
    category: "project",
    description: "Reef 8 open-loop view: list unresolved active findings, stale or unknown facts, and stale or failed diagnostic runs so an agent can see what still needs attention without rerunning broad checks.",
    annotations: toolAnnotations("project_open_loops"),
    inputSchema: ProjectOpenLoopsToolInputSchema,
    outputSchema: ProjectOpenLoopsToolOutputSchema,
    execute: (input, options) => projectOpenLoopsTool(input as never, options),
  },
  {
    name: "verification_state",
    category: "project",
    description: "Reef 8 verification state view: summarize whether cached diagnostic runs still cover the current working-tree overlay, including file-scoped recent runs, watcher diagnostic state, files modified after successful checks, and suggested verification actions. With files, runs only count when project-wide or scoped to those files.",
    annotations: toolAnnotations("verification_state"),
    inputSchema: VerificationStateToolInputSchema,
    outputSchema: VerificationStateToolOutputSchema,
    execute: (input, options) => verificationStateTool(input as never, options),
  },
  {
    name: "project_conventions",
    category: "project",
    description: "Reef 9 convention view: surface explicit convention facts plus profile/index/rule-derived convention candidates such as auth guards, runtime boundaries, generated paths, route patterns, and schema usage conventions.",
    annotations: toolAnnotations("project_conventions"),
    inputSchema: ProjectConventionsToolInputSchema,
    outputSchema: ProjectConventionsToolOutputSchema,
    execute: (input, options) => projectConventionsTool(input as never, options),
  },
  {
    name: "rule_memory",
    category: "project",
    description: "Reef 9 rule-memory view: aggregate Reef rule descriptors and finding history so agents can see which rules are active, acknowledged, resolved, or suppressed before making changes.",
    annotations: toolAnnotations("rule_memory"),
    inputSchema: RuleMemoryToolInputSchema,
    outputSchema: RuleMemoryToolOutputSchema,
    execute: (input, options) => ruleMemoryTool(input as never, options),
  },
  {
    name: "evidence_confidence",
    category: "context",
    description: "Reef 10 evidence-confidence view: label facts and findings as verified_live, fresh_indexed, stale_indexed, fuzzy_semantic, historical, contradicted, or unknown so model-facing tools can prefer trustworthy evidence.",
    annotations: toolAnnotations("evidence_confidence"),
    inputSchema: EvidenceConfidenceToolInputSchema,
    outputSchema: EvidenceConfidenceToolOutputSchema,
    execute: (input, options) => evidenceConfidenceTool(input as never, options),
  },
  {
    name: "evidence_conflicts",
    category: "context",
    description: "Reef 10 conflict view: surface stale indexed evidence, explicit conflict facts, and findings that report incorrect or contradictory evidence, with suggested cross-check actions.",
    annotations: toolAnnotations("evidence_conflicts"),
    inputSchema: EvidenceConflictsToolInputSchema,
    outputSchema: EvidenceConflictsToolOutputSchema,
    execute: (input, options) => evidenceConflictsTool(input as never, options),
  },
  {
    name: "reef_known_issues",
    category: "context",
    description: "Reef warm issue query: answer \"have any errors?\" from maintained Reef findings and diagnostic readiness state without launching broad lint or typecheck commands.",
    annotations: toolAnnotations("reef_known_issues"),
    inputSchema: ReefKnownIssuesToolInputSchema,
    outputSchema: ReefKnownIssuesToolOutputSchema,
    execute: (input, options) => reefKnownIssuesTool(input as never, options),
  },
  {
    name: "reef_agent_status",
    category: "context",
    description: "Reef agent-loop status summary: report maintained known issues, changed files needing verification, stale diagnostic sources, schema freshness, watcher degradation, and background queue state. Never edits files.",
    annotations: toolAnnotations("reef_agent_status"),
    inputSchema: ReefAgentStatusToolInputSchema,
    outputSchema: ReefAgentStatusToolOutputSchema,
    execute: (input, options) => reefAgentStatusTool(input as never, options),
  },
  {
    name: "db_ping",
    category: "db",
    description: "Read-only database tool: verify connectivity and surface platform, version, schemas, and transaction state.",
    annotations: toolAnnotations("db_ping"),
    inputSchema: DbPingToolInputSchema,
    outputSchema: DbPingToolOutputSchema,
    execute: (input, options) => dbPingTool(input as never, options),
  },
  {
    name: "db_columns",
    category: "db",
    description: "Read-only database tool for column questions: inspect only columns and primary-key details for a table via pg_catalog.",
    annotations: toolAnnotations("db_columns"),
    inputSchema: DbColumnsToolInputSchema,
    outputSchema: DbColumnsToolOutputSchema,
    execute: (input, options) => dbColumnsTool(input as never, options),
  },
  {
    name: "db_fk",
    category: "db",
    description: "Read-only database tool for relationship questions: inspect inbound and outbound foreign-key references for a table via pg_catalog.",
    annotations: toolAnnotations("db_fk"),
    inputSchema: DbFkToolInputSchema,
    outputSchema: DbFkToolOutputSchema,
    execute: (input, options) => dbFkTool(input as never, options),
  },
  {
    name: "db_rls",
    category: "db",
    description: "Read-only database tool for security questions: inspect row-level security state and policies for a table via pg_catalog.",
    annotations: toolAnnotations("db_rls"),
    inputSchema: DbRlsToolInputSchema,
    outputSchema: DbRlsToolOutputSchema,
    execute: (input, options) => dbRlsTool(input as never, options),
  },
  {
    name: "db_rpc",
    category: "db",
    description: "Read-only database tool for function questions: inspect one stored procedure or function signature, args, return shape, language, and security.",
    annotations: toolAnnotations("db_rpc"),
    inputSchema: DbRpcToolInputSchema,
    outputSchema: DbRpcToolOutputSchema,
    execute: (input, options) => dbRpcTool(input as never, options),
  },
  {
    name: "db_table_schema",
    category: "db",
    description: "Read-only database tool for full table shape: inspect columns, indexes, constraints, foreign keys, RLS, and triggers.",
    annotations: toolAnnotations("db_table_schema"),
    inputSchema: DbTableSchemaToolInputSchema,
    outputSchema: DbTableSchemaToolOutputSchema,
    execute: (input, options) => dbTableSchemaTool(input as never, options),
  },
  traceFileTool,
  preflightTableTool,
  crossSearchTool,
  traceEdgeTool,
  traceErrorTool,
  traceTableTool,
  traceRpcTool,
] as const;

const TOOL_DEFINITION_MAP: Map<string, MakoToolDefinition<string>> = new Map();

for (const tool of TOOL_DEFINITIONS) {
  TOOL_DEFINITION_MAP.set(tool.name, tool);
}

export function listToolDefinitions(): ToolDefinitionSummary[] {
  return TOOL_DEFINITIONS.map((tool) => ({
    name: tool.name,
    category: tool.category,
    description: tool.description,
    annotations: ToolAnnotationsSchema.parse(tool.annotations),
    inputSchema: schemaToJson(tool.inputSchema, `${tool.name}Input`, {
      useRootRefs: tool.category === "artifact",
    }),
    outputSchema: schemaToJson(withToolHintsSchema(tool.outputSchema), `${tool.name}Output`, {
      useRootRefs: tool.category === "artifact",
    }),
  }));
}

export function getToolDefinition(name: string): MakoToolDefinition<string> | undefined {
  return TOOL_DEFINITION_MAP.get(name);
}

export function registerToolDefinition(definition: MakoToolDefinition<string>): void {
  TOOL_DEFINITION_MAP.set(definition.name, definition);
}

export function unregisterToolDefinition(name: string): void {
  if ((TOOL_DEFINITIONS as readonly MakoToolDefinition[]).some((tool) => tool.name === name)) {
    throw new Error(`Cannot unregister built-in tool: ${name}`);
  }

  TOOL_DEFINITION_MAP.delete(name);
}
